"""log visitor info

Revision ID: 5511b34bca35
Revises: c8f72dd39958
Create Date: 2023-06-24 04:53:36.181951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5511b34bca35'
down_revision = 'c8f72dd39958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_visited', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('browser', sa.String(length=20), nullable=True),
    sa.Column('operating_system', sa.String(length=10), nullable=True),
    sa.Column('device_type', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postal', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=20), nullable=True),
    sa.Column('page', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitors')
    # ### end Alembic commands ###
