"""add show_on_main attribute to project object

Revision ID: c8f72dd39958
Revises: 29386988d763
Create Date: 2023-06-24 01:34:01.863540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f72dd39958'
down_revision = '29386988d763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_on_main', sa.Boolean(), server_default='false', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('show_on_main')

    # ### end Alembic commands ###
