"""migration test

Revision ID: dbcfe9f303ad
Revises: 
Create Date: 2023-06-20 00:26:01.604820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcfe9f303ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('fa_icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fa_icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
